version: '3.3'

services:

  blackjack:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    depends_on:
      - mongo
    stdin_open: true
    tty: true
    volumes:
      - .:/app
     

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=blackjack
    ports:
      - "27017:27017"
